name = "futbol-page"
account_id = "27003167a1aa791e96abe11a8324b346"
workers_dev = true
compatibility_date = "2025-05-07"

[site]
bucket = "./dist"              # Aquí se encuentra la salida de vite
# "entry-point" eliminado porque ya no es necesario

[build]
command = "npm run build"
# "upload.format" eliminado: wrangler detecta automáticamente el formato

[[routes]]
pattern = "/api/*"
script = "api"

[[routes]]
pattern = "/api/comments/*"
script = "comments"
